### ISSUE TITLE
test failing

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-relion#422]
```
[   FAILED ] TestRelionExtractParticles.setUpClass


Traceback (most recent call last):
File "/public/EM/Scipion/miniconda3/envs/scipion3/lib/python3.8/unittest/suite.py", line 163, in _handleClassSetUp
setUpClass()
File "/public/EM/Scipion/scipion-dev/scipion-em-plugins/scipion-em-relion/relion/tests/test_protocols_2d.py", line 414, in setUpClass
cls.protPP = cls.runFakePicking(cls.protDown.outputMicrographs, cls.allCrdsDir)
AttributeError: 'XmippProtPreprocessMicrographs' object has no attribute 'outputMicrographs'
```

**Comment by azazellochg** [comment]
caused by https://github.com/scipion-em/scipion-pyworkflow/pull/564
